# Generated by Django 3.0 on 2019-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.FileField(default='', upload_to='album_logo/'),
        ),
    ]
