# Generated by Django 2.2.7 on 2019-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='title',
            field=models.CharField(default='i', max_length=50),
        ),
    ]
