# Generated by Django 2.2.7 on 2019-12-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191208_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pictures',
        ),
    ]
