# Generated by Django 2.2.7 on 2020-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200112_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='Avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
