# Generated by Django 3.0.2 on 2020-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20200127_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='Music_App/static/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
