# Generated by Django 3.0.2 on 2020-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20200127_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='Music_App/static/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
