# Generated by Django 3.0.2 on 2020-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200127_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
    ]
